// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWDcSrANukdW1zYXyvOOuP3PpXVqT8HQc',
    appId: '1:667537956733:web:bd9f55a3fe5defd0257614',
    messagingSenderId: '667537956733',
    projectId: 'bus-tracker-c69ef',
    authDomain: 'bus-tracker-c69ef.firebaseapp.com',
    storageBucket: 'bus-tracker-c69ef.firebasestorage.app',
    measurementId: 'G-Q2PF515CQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvxiNsSK8fR3-tWwyvRhmrmwBBW3gcH6M',
    appId: '1:667537956733:android:f85add93d72bfc2c257614',
    messagingSenderId: '667537956733',
    projectId: 'bus-tracker-c69ef',
    storageBucket: 'bus-tracker-c69ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYvadAbAOIkjM4ZKr89ZbjsQkDJHCsNvY',
    appId: '1:667537956733:ios:ce013134b77f2634257614',
    messagingSenderId: '667537956733',
    projectId: 'bus-tracker-c69ef',
    storageBucket: 'bus-tracker-c69ef.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYvadAbAOIkjM4ZKr89ZbjsQkDJHCsNvY',
    appId: '1:667537956733:ios:ce013134b77f2634257614',
    messagingSenderId: '667537956733',
    projectId: 'bus-tracker-c69ef',
    storageBucket: 'bus-tracker-c69ef.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDcSrANukdW1zYXyvOOuP3PpXVqT8HQc',
    appId: '1:667537956733:web:758c9fb29c47fabf257614',
    messagingSenderId: '667537956733',
    projectId: 'bus-tracker-c69ef',
    authDomain: 'bus-tracker-c69ef.firebaseapp.com',
    storageBucket: 'bus-tracker-c69ef.firebasestorage.app',
    measurementId: 'G-X2754685PS',
  );

}